name: gsas-AustCalc
channels:
  - defaults
  - briantoby
dependencies:
  - gsas2pkg=2.2.0
  - python
  - plotly
  - pandas
  - numpy
  - matplotlib
  - dash
  - flask
  - pip
  - sphinx
  - pymc3=3.6
  - arviz=0.11.2
  - statsmodels
  - pytest
  - pip:
    - dash-bootstrap-components
    - dash-extensions==0.0.71
