name: gsas-AustCalc
channels:
  - defaults
  - briantoby
  - conda-forge
dependencies:
  - gsas2pkg=2.2.0
  - python
  - plotly
  - pandas
  - numpy
  - matplotlib
  - dash
  - flask
  - pip
  - sphinx
  - pytest
  - cmdstanpy
  - pip:
    - dash-bootstrap-components
    - dash-extensions==0.0.71
    - kaleido
    - dash-unload-component