name: gsas-AustCalc
channels:
  - defaults
  - briantoby
dependencies:
  - gsas2pkg=2.2.0
  - python
  - plotly
  - pandas
  - numpy
  - matplotlib
  - dash
  - flask
  - pip
  - sphinx
  - pip:
    - dash-bootstrap-components
